/**
 * Data access layer for Firebase (Auth + Firestore).
 * Every page reads/writes through this file so the storage backend can be
 * swapped later without touching page logic. Do not edit this file to
 * change content — content lives in Firestore and is edited via editor.html.
 */

const HAJJ_DOC = { collection: 'hajj_data', doc: 'content' };

function ensureFirebase() {
  if (!window.firebase) throw new Error('Firebase SDK failed to load. Check the script order on this page.');
  if (!firebase.apps.length) firebase.initializeApp(FIREBASE_CONFIG);
  return firebase;
}

function fbAuth() { return ensureFirebase().auth(); }
function fbDb() { return ensureFirebase().firestore(); }

/** Reads the latest published content snapshot. Returns null if nothing has been published yet. */
async function loadData() {
  const snap = await fbDb().collection(HAJJ_DOC.collection).doc(HAJJ_DOC.doc).get();
  return snap.exists ? snap.data() : null;
}

/** Publishes a new content snapshot, fully replacing the previous one. Requires an authenticated user. */
async function saveData(data) {
  await fbDb().collection(HAJJ_DOC.collection).doc(HAJJ_DOC.doc).set(data);
}
